In [ ]:
#固定时间间隔切分视频
import subprocess
import os
path = 'G:\\salmon\\5am'  # 待切割视频存储目录
video_list = os.listdir(path)
print(path)
print(video_list)
delta_X = 10   # 每10s切割
save_path = 'G:\\salmon_result'
mark = 0 

# 获取视频的时长
def get_length(filename):
    result = subprocess.run(["ffprobe", "-v", "error", "-show_entries",
                             "format=duration", "-of",
                             "default=noprint_wrappers=1:nokey=1", filename],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT)
    return float(result.stdout)
 
for file_name in video_list:
    min = int(get_length(os.path.join(path, file_name))) // 60    # file_name视频的分钟数
    second = int(get_length(os.path.join(path, file_name))) % 60    # file_name视频的秒数
    for i in range(min+1):
        if second >= delta_X:   # 至少保证一次切割
            start_time = 0
            end_time = start_time+delta_X
            for j in range((second//10)+1):
                min_temp = str(i)
                start = str(start_time)
                end = str(end_time)
                # crop video
                # 保证两位数
                if len(str(min_temp)) == 1:
                    min_temp = '0'+str(min_temp)
                if len(str(start_time)) == 1:
                    start = '0'+str(start_time)
                if len(str(end_time)) == 1:
                    end = '0'+str(end_time)
                
                # 设置保存视频的名字
                if len(str(mark)) < 6:
                    name = '0'*(6-len(str(mark))-1)+str(mark)
                else:
                    name = str(mark)
                command = 'ffmpeg -i {} -ss 00:{}:{} -to 00:{}:{} -strict -2 {}'.format(os.path.join(path,file_name),
                                                min_temp,start,min_temp,end,
                                                os.path.join(save_path,'id'+str(name))+'.mp4')
                mark += 1
                os.system(command)
                if i != min or (i == min and (end_time+delta_X) < second):
                    start_time += delta_X
                    end_time += delta_X
                elif (end_time+delta_X) <= second:
                    start_time += delta_X
                    end_time += delta_X
                elif (end_time+delta_X) > second:  # 最后不足delta_X的部分会被舍弃
                    break

print('success!')


In [2]:
#从视频隔固定时间抽帧

import cv2
import os
#先读取文件夹下的视频列表
fileList=os.listdir('C:\\Study\\salmon_video_cut\\active')

n = 0 #文件夹数量
a = 1 #图片编号

for i in fileList:
    
    #依次读取视频
    cap = cv2.VideoCapture("C:\\Study\\salmon_video_cut\\active\\"+fileList[n])
    
    #创建对应视频名称的文件夹                
    #os.mkdir(r'C:\\Study\\salmon_pic\\'+fileList[n][:-4])
    
    #保存图片的路径
    #image_path="C:\\Study\\salmon_pic\\"+fileList[n][:-4]
    image_path="C:\\Study\\salmon_det\\active"
    
    c = 1 #每个视频的帧数
    frameRate = 10  # 帧数截取间隔
    #a = 1 #图片编号
    while(True):
        ret, frame = cap.read()
        if ret:
            if(c % frameRate == 0):
                #print("开始截取视频第" + str(c) + " 帧")
                # 这里就可以做一些操作了：显示截取的帧图片、保存截取帧到本地
                cv2.imwrite(image_path+ os.sep + str(a).zfill(6) + '.jpg', frame)  # 这里是将截取的图像保存在本地
                a=a+1
            c+=1
            cv2.waitKey(0)
        else:
            print(fileList[n][:-4]+"保存完成")
            break
    cap.release()
    n=n+1
print("所有帧都已经保存完成")

A00001保存完成
A00002保存完成
A00003保存完成
A00004保存完成
A00005保存完成
A00006保存完成
A00007保存完成
A00008保存完成
A00009保存完成
A00010保存完成
A00011保存完成
A00012保存完成
A00013保存完成
A00014保存完成
A00015保存完成
A00016保存完成
A00017保存完成
A00018保存完成
A00019保存完成
A00020保存完成
A00021保存完成
A00022保存完成
A00023保存完成
A00024保存完成
A00025保存完成
A00026保存完成
A00027保存完成
A00028保存完成
A00029保存完成
A00030保存完成
A00031保存完成
A00032保存完成
A00033保存完成
A00034保存完成
A00035保存完成
A00036保存完成
A00037保存完成
A00038保存完成
A00039保存完成
A00040保存完成
A00041保存完成
A00042保存完成
A00043保存完成
A00044保存完成
A00045保存完成
A00046保存完成
A00047保存完成
A00048保存完成
A00049保存完成
A00050保存完成
A00051保存完成
A00052保存完成
A00053保存完成
A00054保存完成
A00055保存完成
A00056保存完成
A00057保存完成
A00058保存完成
A00059保存完成
A00060保存完成
A00061保存完成
A00062保存完成
A00063保存完成
A00064保存完成
A00065保存完成
A00066保存完成
A00067保存完成
A00068保存完成
A00069保存完成
A00070保存完成
A00071保存完成
A00072保存完成
A00073保存完成
A00074保存完成
A00075保存完成
A00076保存完成
A00077保存完成
A00078保存完成
A00079保存完成
A00080保存完成
A00081保存完成
A00082保存完成
A00083保存完成
A00084保存完成
A00085保存完成
A00086保存完成
A00087保存完成
A00088保存完成
A00089保存完成
A00090保存完成
A00091保存完成

In [29]:
#批量修改txt文件名

import os
path='C:\\Study\\salmon_pic\\active\\salmon\\labels\\val'
print(path)

#获取该目录下所有文件，存入列表中
fileList=os.listdir(path)

n=0
z=0 #索引
for i in fileList:
    
    #设置旧文件名（就是路径+文件名）
    oldname=path+ os.sep + fileList[z]   # os.sep添加系统分隔符
    
    #设置新文件名
    #newname=path + os.sep +'N'+str(n+1).zfill(5)+'.mp4'
    newname=path + os.sep +fileList[z][:-4].zfill(5)+'.txt'
    #newname=path + os.sep +str(int(fileList[z][:-4])+300).zfill(5)+'.txt'
    
    os.rename(oldname,newname)   #用os模块中的rename方法对文件改名
    print(oldname,'======>',newname)
    
    n+=1
    z+=1

C:\Study\salmon_pic\active\salmon\labels\val
C:\Study\salmon_pic\active\salmon\labels\val\1.txt ======> C:\Study\salmon_pic\active\salmon\labels\val\00001.txt
C:\Study\salmon_pic\active\salmon\labels\val\10.txt ======> C:\Study\salmon_pic\active\salmon\labels\val\00010.txt
C:\Study\salmon_pic\active\salmon\labels\val\11.txt ======> C:\Study\salmon_pic\active\salmon\labels\val\00011.txt
C:\Study\salmon_pic\active\salmon\labels\val\12.txt ======> C:\Study\salmon_pic\active\salmon\labels\val\00012.txt
C:\Study\salmon_pic\active\salmon\labels\val\13.txt ======> C:\Study\salmon_pic\active\salmon\labels\val\00013.txt
C:\Study\salmon_pic\active\salmon\labels\val\14.txt ======> C:\Study\salmon_pic\active\salmon\labels\val\00014.txt
C:\Study\salmon_pic\active\salmon\labels\val\15.txt ======> C:\Study\salmon_pic\active\salmon\labels\val\00015.txt
C:\Study\salmon_pic\active\salmon\labels\val\16.txt ======> C:\Study\salmon_pic\active\salmon\labels\val\00016.txt
C:\Study\salmon_pic\active\salmon\la

In [8]:
#批量修改.mp4/.jpg文件名
import os
path='C:\\Study\\salmon_mot\\MOTSALMON\\test\\MOTSALMON-04\\img4'
print(path)

#获取该目录下所有文件，存入列表中
fileList=os.listdir(path)

n=0
z=0 #索引
for i in fileList:
    
    #设置旧文件名（就是路径+文件名）
    oldname=path+ os.sep + fileList[z]   # os.sep添加系统分隔符
    #print(str(int(fileList[z][:-4])-300).zfill(5))
    #设置新文件名
    newname=path+os.sep+str(int(fileList[z][:-4])-600).zfill(5)+'.jpg'
    #newname=path + os.sep +'N'+str(n+1).zfill(5)+'.mp4'
    #newname=path + os.sep +str(n+1).zfill(5)+'.jpg'
    
    print(oldname,'======>',newname)
    os.rename(oldname,newname)   #用os模块中的rename方法对文件改名
    
    n+=1
    z+=1

C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4
C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00601.jpg ======> C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00001.jpg
C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00602.jpg ======> C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00002.jpg
C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00603.jpg ======> C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00003.jpg
C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00604.jpg ======> C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00004.jpg
C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00605.jpg ======> C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00005.jpg
C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00606.jpg ======> C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00006.jpg
C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00607.jpg ======> C:\Study\salmon_mot\MOTSALMON\test\MOTSALMON-04\img4\00007.jpg
C:\Study\

In [4]:
#通过ffmpege抽取关键帧

import os
import cv2
import subprocess 

filename = r'G:\salmon\5am\GH016787_5am.mp4' 


def get_frame_types(video_fn):
    command = 'ffprobe -v error -show_entries frame=pict_type -of default=noprint_wrappers=1'.split()
    out = subprocess.check_output(command + [video_fn]).decode()
    frame_types = out.replace('pict_type=', '').split()
    return zip(range(len(frame_types)), frame_types)


from PIL import Image


def save_i_keyframes(video_fn):
    frame_types = get_frame_types(video_fn)
    i_frames = [x[0] for x in frame_types if x[1] == 'I']
    if i_frames:
        basename = os.path.splitext(os.path.basename(video_fn))[0]
        res_dir = os.path.join(os.path.dirname(video_fn), 'frame')
        os.mkdir(res_dir)
        cap = cv2.VideoCapture(video_fn)
        for frame_no in i_frames:
            cap.set(cv2.CAP_PROP_POS_FRAMES, frame_no)
            ret, frame = cap.read()
            outname = basename + '_i_frame_' + str(frame_no) + '.jpg'
            Image.fromarray(frame).save(os.path.join(res_dir, outname))
            print('Saved: ' + outname)
        cap.release()
    else:
        print('No I-frames in ' + video_fn)


if __name__ == '__main__':
    save_i_keyframes(filename)


Saved: GH016787_5am_i_frame_0.jpg
Saved: GH016787_5am_i_frame_128.jpg
Saved: GH016787_5am_i_frame_256.jpg
Saved: GH016787_5am_i_frame_384.jpg
Saved: GH016787_5am_i_frame_512.jpg
Saved: GH016787_5am_i_frame_640.jpg
Saved: GH016787_5am_i_frame_768.jpg
Saved: GH016787_5am_i_frame_896.jpg
Saved: GH016787_5am_i_frame_1024.jpg
Saved: GH016787_5am_i_frame_1152.jpg
Saved: GH016787_5am_i_frame_1280.jpg
Saved: GH016787_5am_i_frame_1408.jpg
Saved: GH016787_5am_i_frame_1536.jpg
Saved: GH016787_5am_i_frame_1664.jpg
Saved: GH016787_5am_i_frame_1792.jpg
Saved: GH016787_5am_i_frame_1920.jpg
Saved: GH016787_5am_i_frame_2048.jpg
Saved: GH016787_5am_i_frame_2176.jpg
Saved: GH016787_5am_i_frame_2304.jpg
Saved: GH016787_5am_i_frame_2432.jpg
Saved: GH016787_5am_i_frame_2560.jpg
Saved: GH016787_5am_i_frame_2688.jpg
Saved: GH016787_5am_i_frame_2816.jpg
Saved: GH016787_5am_i_frame_2944.jpg
Saved: GH016787_5am_i_frame_3072.jpg
Saved: GH016787_5am_i_frame_3200.jpg
Saved: GH016787_5am_i_frame_3328.jpg
Saved: GH01

In [2]:
# 伽马变换
def gamma(image):
    fgamma = 0.5
    image_gamma = np.uint8(np.power((np.array(image) / 255.0), fgamma) * 255.0)
    cv2.normalize(image_gamma, image_gamma, 0, 255, cv2.NORM_MINMAX)
    cv2.convertScaleAbs(image_gamma, image_gamma)
    return image_gamma


In [8]:
#传统方法提升亮度
import os
import cv2
import numpy as np
from PIL import Image, ImageEnhance

data_path = 'C:\\Study\\salmon_pic\\active\\A00004\\'

# 设置增强因子，0.0为黑色，1.0为原始，大于1.0为更亮
factor = 1.2

img_list = os.listdir(data_path)

if len(img_list) == 0:
    print('empty!')
    exit()
for img_name in img_list:
    
    #img = cv2.imread(os.path.join(data_path, img_name))
    img = Image.open(os.path.join(data_path, img_name))
    img_bri=ImageEnhance.Brightness(img).enhance(factor)
    #img_gamma=gamma(img_bri)
    #cv2.imwrite('C:\\Study\\salmon_pic\\active\\A2\\'+img_name,img_bri)
    img_bri.save('C:\\Study\\salmon_pic\\active\\A2\\'+img_name)


In [2]:
#ACE图像增强
import cv2
import numpy as np
import math
import matplotlib.pyplot as plt

#线性拉伸处理
#去掉最大最小0.5%的像素值 线性拉伸至[0,1]
def stretchImage(data, s=0.005, bins = 2000):   
    ht = np.histogram(data, bins);
    d = np.cumsum(ht[0])/float(data.size)
    lmin = 0; lmax=bins-1
    while lmin<bins:
        if d[lmin]>=s:
            break
        lmin+=1
    while lmax>=0:
        if d[lmax]<=1-s:
            break
        lmax-=1
    return np.clip((data-ht[1][lmin])/(ht[1][lmax]-ht[1][lmin]), 0,1)

#根据半径计算权重参数矩阵
g_para = {}
def getPara(radius = 5):                        
    global g_para
    m = g_para.get(radius, None)
    if m is not None:
        return m
    size = radius*2+1
    m = np.zeros((size, size))
    for h in range(-radius, radius+1):
        for w in range(-radius, radius+1):
            if h==0 and w==0:
                continue
            m[radius+h, radius+w] = 1.0/math.sqrt(h**2+w**2)
    m /= m.sum()
    g_para[radius] = m
    return m

#常规的ACE实现
def zmIce(I, ratio=4, radius=300):                     
    para = getPara(radius)
    height,width = I.shape
    zh = []
    zw = []
    n = 0
    while n < radius:
        zh.append(0)
        zw.append(0)
        n += 1
    for n in range(height):
        zh.append(n)
    for n in range(width):
        zw.append(n)
    n = 0
    while n < radius:
        zh.append(height-1)
        zw.append(width-1)
        n += 1
    #print(zh)
    #print(zw)
    
    Z = I[np.ix_(zh, zw)]
    res = np.zeros(I.shape)
    for h in range(radius*2+1):
        for w in range(radius*2+1):
            if para[h][w] == 0:
                continue
            res += (para[h][w] * np.clip((I-Z[h:h+height, w:w+width])*ratio, -1, 1))
    return res

#单通道ACE快速增强实现
def zmIceFast(I, ratio, radius):
    #print(I)
    height, width = I.shape[:2]
    if min(height, width) <=2:
        return np.zeros(I.shape)+0.5
    Rs = cv2.resize(I, (int((width+1)/2), int((height+1)/2)))
    Rf = zmIceFast(Rs, ratio, radius)             #递归调用
    Rf = cv2.resize(Rf, (width, height))
    Rs = cv2.resize(Rs, (width, height))
 
    return Rf+zmIce(I,ratio, radius)-zmIce(Rs,ratio,radius)   

#rgb三通道分别增强 ratio是对比度增强因子 radius是卷积模板半径          
def zmIceColor(I, ratio=4, radius=3):               
    res = np.zeros(I.shape)
    for k in range(3):
        res[:,:,k] = stretchImage(zmIceFast(I[:,:,k], ratio, radius))
    return res


In [3]:
import os
import cv2
from PIL import Image, ImageEnhance

data_path = 'C:\\Study\\salmon_pic\\active\\A00004\\'

img_list = os.listdir(data_path)

if len(img_list) == 0:
    print('empty!')
    exit()
    
for img_name in img_list:
    img = cv2.imread(os.path.join(data_path, img_name))
    res = zmIceColor(img/255.0)*255
    cv2.imwrite('C:\\Study\\salmon_pic\\active\\A2\\'+img_name, res)
    
    #img = cv2.imread(os.path.join(data_path, img_name))
    #img = Image.open(os.path.join(data_path, img_name))
    #cv2.imwrite('C:\\Study\\salmon_pic\\active\\A1\\'+img_name, ImageEnhance.Brightness(img).enhance(factor))
    #ImageEnhance.Brightness(img).enhance(factor).save('C:\\Study\\salmon_pic\\active\\A2\\'+img_name)


[[0.29803922 0.29803922 0.29803922 ... 0.34509804 0.34509804 0.34509804]
 [0.29803922 0.29803922 0.29803922 ... 0.34509804 0.34509804 0.34509804]
 [0.29803922 0.29803922 0.29803922 ... 0.34509804 0.34509804 0.34509804]
 ...
 [0.21568627 0.21568627 0.21568627 ... 0.19215686 0.19215686 0.19215686]
 [0.21960784 0.21960784 0.21960784 ... 0.19215686 0.19215686 0.19215686]
 [0.21960784 0.21960784 0.21960784 ... 0.19215686 0.19215686 0.19215686]]
[[0.29803922 0.29803922 0.29803922 ... 0.34509804 0.34509804 0.34509804]
 [0.29803922 0.29803922 0.29803922 ... 0.34509804 0.34509804 0.34509804]
 [0.29803922 0.29803922 0.29803922 ... 0.34509804 0.34509804 0.34509804]
 ...
 [0.20588235 0.20686275 0.20490196 ... 0.19607843 0.19607843 0.19607843]
 [0.21372549 0.21372549 0.21176471 ... 0.19215686 0.19215686 0.19215686]
 [0.21960784 0.21960784 0.21764706 ... 0.19215686 0.19215686 0.19215686]]
[[0.29803922 0.29803922 0.29411765 ... 0.34509804 0.34509804 0.34509804]
 [0.29803922 0.29803922 0.29411765 ... 

[[0.29019608 0.29019608 0.29019608 ... 0.31764706 0.31764706 0.31764706]
 [0.29019608 0.29019608 0.29019608 ... 0.31764706 0.31764706 0.31764706]
 [0.29019608 0.29019608 0.29019608 ... 0.31764706 0.31764706 0.31764706]
 ...
 [0.21960784 0.21960784 0.21960784 ... 0.18431373 0.18431373 0.18431373]
 [0.22352941 0.22352941 0.22352941 ... 0.18431373 0.18431373 0.18431373]
 [0.22352941 0.22352941 0.22352941 ... 0.18431373 0.18431373 0.18431373]]
[[0.29019608 0.29019608 0.29019608 ... 0.31764706 0.31764706 0.31764706]
 [0.29019608 0.29019608 0.29019608 ... 0.31764706 0.31764706 0.31764706]
 [0.29019608 0.29019608 0.29019608 ... 0.31764706 0.31764706 0.31764706]
 ...
 [0.20980392 0.21078431 0.20882353 ... 0.18823529 0.18823529 0.18823529]
 [0.21764706 0.21764706 0.21568627 ... 0.18431373 0.18431373 0.18431373]
 [0.22352941 0.22352941 0.22156863 ... 0.18431373 0.18431373 0.18431373]]
[[0.29019608 0.29019608 0.29411765 ... 0.31764706 0.31764706 0.31764706]
 [0.29019608 0.29019608 0.29411765 ... 

[[0.32941176 0.32941176 0.32941176 ... 0.36078431 0.36078431 0.36078431]
 [0.32941176 0.32941176 0.32941176 ... 0.36078431 0.36078431 0.36078431]
 [0.32941176 0.32941176 0.32941176 ... 0.36078431 0.36078431 0.36078431]
 ...
 [0.20784314 0.20784314 0.20784314 ... 0.27843137 0.27843137 0.27843137]
 [0.21176471 0.21176471 0.21176471 ... 0.27843137 0.27843137 0.27843137]
 [0.21176471 0.21176471 0.21176471 ... 0.27843137 0.27843137 0.27843137]]
[[0.32941176 0.32941176 0.32941176 ... 0.36078431 0.36078431 0.36078431]
 [0.32941176 0.32941176 0.32941176 ... 0.36078431 0.36078431 0.36078431]
 [0.32941176 0.32941176 0.32941176 ... 0.36078431 0.36078431 0.36078431]
 ...
 [0.20196078 0.20196078 0.20490196 ... 0.27843137 0.27843137 0.27843137]
 [0.20784314 0.20784314 0.20882353 ... 0.27843137 0.27843137 0.27843137]
 [0.21176471 0.21176471 0.21176471 ... 0.27843137 0.27843137 0.27843137]]
[[0.32941176 0.3254902  0.31764706 ... 0.36078431 0.36078431 0.36078431]
 [0.32941176 0.3254902  0.31764706 ... 

[[0.29803922 0.29803922 0.29803922 ... 0.34117647 0.34117647 0.34117647]
 [0.29803922 0.29803922 0.29803922 ... 0.34117647 0.34117647 0.34117647]
 [0.29803922 0.29803922 0.29803922 ... 0.34117647 0.34117647 0.34117647]
 ...
 [0.18431373 0.18431373 0.18431373 ... 0.22352941 0.22352941 0.22352941]
 [0.18431373 0.18431373 0.18431373 ... 0.22352941 0.22352941 0.22352941]
 [0.18431373 0.18431373 0.18431373 ... 0.22352941 0.22352941 0.22352941]]
[[0.29803922 0.29607843 0.29117647 ... 0.34117647 0.34117647 0.34117647]
 [0.29803922 0.29607843 0.29117647 ... 0.34117647 0.34019608 0.34117647]
 [0.29803922 0.29607843 0.29117647 ... 0.34313725 0.34313725 0.34313725]
 ...
 [0.18431373 0.18431373 0.18431373 ... 0.22352941 0.22352941 0.22352941]
 [0.18431373 0.18431373 0.18431373 ... 0.22352941 0.22352941 0.22352941]
 [0.18431373 0.18431373 0.18431373 ... 0.22352941 0.22352941 0.22352941]]
[[0.29705882 0.29264706 0.29411765 ... 0.33406863 0.33872549 0.34093137]
 [0.29705882 0.29411765 0.29215686 ... 

[[0.29803922 0.29803922 0.29803922 ... 0.3254902  0.3254902  0.3254902 ]
 [0.29803922 0.29803922 0.29803922 ... 0.3254902  0.3254902  0.3254902 ]
 [0.29803922 0.29803922 0.29803922 ... 0.3254902  0.3254902  0.3254902 ]
 ...
 [0.20392157 0.20392157 0.20392157 ... 0.23529412 0.23529412 0.23529412]
 [0.20392157 0.20392157 0.20392157 ... 0.23529412 0.23529412 0.23529412]
 [0.20392157 0.20392157 0.20392157 ... 0.23529412 0.23529412 0.23529412]]
[[0.29803922 0.29607843 0.28333333 ... 0.3254902  0.3254902  0.3254902 ]
 [0.29803922 0.29607843 0.28333333 ... 0.3254902  0.3245098  0.3254902 ]
 [0.29803922 0.29607843 0.28333333 ... 0.32745098 0.32745098 0.32745098]
 ...
 [0.20392157 0.20392157 0.20392157 ... 0.23529412 0.23529412 0.23529412]
 [0.20392157 0.20392157 0.20392157 ... 0.23529412 0.23529412 0.23529412]
 [0.20392157 0.20392157 0.20392157 ... 0.23529412 0.23529412 0.23529412]]
[[0.29705882 0.28480392 0.28431373 ... 0.31838235 0.32303922 0.3252451 ]
 [0.29705882 0.28627451 0.28431373 ... 

KeyboardInterrupt: 

In [10]:
# 限制对比度自适应直方图均衡化CLAHE
def clahe(image):
    b, g, r = cv2.split(image)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    b = clahe.apply(b)
    g = clahe.apply(g)
    r = clahe.apply(r)
    image_clahe = cv2.merge([b, g, r])
    return image_clahe

In [11]:
#CLAHE图像增强
import os
import cv2
from PIL import Image, ImageEnhance

data_path = 'C:\\Study\\salmon_pic\\active\\A00004\\'

img_list = os.listdir(data_path)

if len(img_list) == 0:
    print('empty!')
    exit()
    
for img_name in img_list:
    img = cv2.imread(os.path.join(data_path, img_name))
    res = clahe(img)
    cv2.imwrite('C:\\Study\\salmon_pic\\active\\A2\\'+img_name, res)